stage:
  JAM_TOKEN: CHANGEME
  JAM_URL: https://staging-metadata.osf.io
  COLLECTIONS_PATH: ./collections.js

prod:
  JAM_TOKEN: CHANGEME
  JAM_URL: https://metadata.osf.io
  COLLECTIONS_PATH: ./collections.js

local:
  JAM_TOKEN: CHANGEME
  JAM_URL: http://localhost:1212
  COLLECTIONS_PATH: ./collections.js
